### ISSUE TITLE
Any support for sql.Null[V any]

### ISSUE THREAD

**Issue by esiqveland** [bokwoon95/sq#15]
Any way to include support for `sql.Null[V any]` values in `sq.Row` ?

I suspect this is not really possible due to limitations in Go generics, but I figured I would ask your thoughts on it.

**Comment by bokwoon95** [comment]
Yeah you're right, Go methods cannot be generic so any method on sq.Row cannot be generic. 

Honestly, I'm glad NullString/NullInt64/etc exist because that means that sq.Row can still returns some standardized null types even without being generic. You can still use sq.Null[V any] though, through row.Scan.

```go
func(row *sql.Row) string {
    var nullString sql.Null[string]
    row.Scan(&nullString, "name")
    return nullString.V
}
```
