### ISSUE TITLE
dialect into wrapper/context/global/env/...

### ISSUE THREAD

**Issue by vendelin8** [bokwoon95/sq#7]
Hi,

Thanks for this awesome lib.

There's only one thing I don't like, is that `SetDialect` needs to be called for all queries. Is there any way to remove this, and need to set it only once per project?

I'm thinking of either something like 
```
type SqWrap struct {
  *sql.DB
  Dialect string
}
```

or storing it in a global in sq like `sq.SetDialect` and it would mean for all queries.

Thanks again.

**Comment by dusanradojcic00** [comment]
I also find this frustrating

**Comment by bokwoon95** [comment]
What about using the [`sq.Postgres/sq.MySQL` query builders](https://bokwoon.neocities.org/sq#set-query-dialect)? 

> You can use the sq.SQLite, sq.Postgres, sq.MySQL and sq.SQLServer package-level variables as shorthand for setting the dialect (in order to type less).
>
> ```go
> sq.SQLite.Queryf(query)    // sq.Queryf(query).SetDialect(sq.DialectSQLite)
> sq.Postgres.Queryf(query)  // sq.Queryf(query).SetDialect(sq.DialectPostgres)
> sq.MySQL.Queryf(query)     // sq.Queryf(query).SetDialect(sq.DialectMySQL)
> sq.SQLServer.Queryf(query) // sq.Queryf(query).SetDialect(sq.DialectSQLServer)
> ```

So instead of 

```go
sq.From(table).Where(condition)
```

```go
sq.FetchAll(db, sq.
    From(table).
    Where(condition),
    rowmapper,
)
``` 

you can do

```go
sq.Postgres.From(table).Where(condition) // Sets the query to Postgres
```

```go
sq.FetchAll(db, sq.Postgres.
    From(table).
    Where(condition),
    rowmapper,
)
``` 

It's not as convenient as setting the dialect once and forgetting it, but there's good reason to use the dialect-specific query builders because it allows you to use features supported by that dialect. For example, the Postgres query builder additionally supports [DISTINCT ON](https://pkg.go.dev/github.com/bokwoon95/sq#PostgresSelectQuery.DistinctOn). So like if you know you're only ever going to use Postgres, substitute all calls to `sq.From()` with `sq.Postgres.From()`.

**Comment by dusanradojcic00** [comment]
All right, thank you!

**Comment by bokwoon95** [comment]
Hi, commit caefb688333aaace2bacaa46671338a94daf2579 adds the ability to configure a default dialect globally. Use it like this:

```go
func init() {
    // Sets the default dialect of all queries to Postgres (unless a dialect is
    // explicitly provided).
    sq.DefaultDialect.Store(&sq.DialectPostgres)
}
```

After that if you omit the dialect in FetchOne/FetchCall/Exec/etc, the default dialect is used.
