### ISSUE TITLE
slice in query value

### ISSUE THREAD

**Issue by vendelin8** [bokwoon95/sq#8]
Hi,

I'd like some help with the following:

```
qry := "SELECT COUNT(*) FROM customers WHERE id IN {id}"
values := []any{sql.Named("id", []int{1})}
cnt, err := sq.FetchOneContext(context.Background(), sq.Log(db), sq.Postgres.Queryf(qry, values...), rowToCount)
```

Result:
`SELECT COUNT(*) FROM customers WHERE id IN 1; err={pq: syntax error at or near "$1"}`

I'd expect adding parentheses. If I have multiple values in that param, I get very similar:
`SELECT COUNT(*) FROM customers WHERE id IN 1, 2; err={pq: syntax error at or near "$1"}`

**Comment by bokwoon95** [comment]
This is actually the correct behaviour, placeholder values are expanded in the query string according to [the following logic](https://bokwoon.neocities.org/sq#value-expansion):

1. If the value implements the SQLWriter interface, its WriteSQL method is called.
2. Else if the value is a slice, the slice is expanded into a comma separated list. *<-- (this is what is happening)*
3. Otherwise, a dialect-appropriate placeholder is appended to the query string and the value itself is appended to the args.

So you can reliably count on slices expanding into a comma separated list, and the query should be rewritten with the enclosing parentheses:

```go
qry := "SELECT COUNT(*) FROM customers WHERE id IN ({id})"
values := []any{sql.Named("id", []int{1, 2})}
cnt, err := sq.FetchOneContext(context.Background(), sq.Log(db), sq.Postgres.Queryf(qry, values...), rowToCount)
```
```sql
SELECT COUNT(*) FROM customers WHERE id IN (1, 2)
```

It works like this because slices becoming comma separated lists is useful in more situations:

##  Selecting a list of fields
```go
sq.Postgres.Queryf(
    "SELECT {fields} from {table}",
    sql.Named("fields", []any{sq.Expr("f1"), sq.Expr("f2"), sq.Expr("f3")}),
    sql.Named("table", sq.Expr("tbl")),
)
```
```sql
SELECT f1, f2, f3 FROM tbl
```

## IN values
```go
sq.Postgres.Queryf(
    "SELECT * from tbl WHERE field IN ({values})",
    sq.Named("values", []int{1, 2, 3}),
)
```
```sql
SELECT * FROM tbl WHERE field IN (1, 2, 3)
```

## Function arguments
```go
sq.Postgres.Queryf(
    "SELECT concat({args})",
    sql.Named("args", []string{"a", "b", "c"}),
)
```
```sql
SELECT concat('a', 'b', 'c')
```

If want to omit the enclosing parentheses, you can pass in something that implements the SQLWriter interface and includes enclosing parantheses, like `sq.RowValue`.

```go
sq.Postgres.Queryf(
    "SELECT * from tbl WHERE field IN {rowvalue}",
    sq.Named("rowvalue", sq.RowValue{1, 2, 3}),
)
```
```sql
SELECT * FROM tbl WHERE field IN (1, 2, 3)
```

**Comment by vendelin8** [comment]
Thanks, sounds reasonable.
